---
- name: Run CometBFT container
  community.general.docker_container:
    user: 100
    name: cometbft_container
    default_host_ip: 0.0.0.0
    image: ghcr.io/saikatharryc/cometbft/cometbft:v0.37.5-3
    image_name_mismatch: recreate
    state: started
    restart_policy: on-failure
    command: [start, --proxy_app, penumbra_container:26658, --moniker, saikat]
    keep_volumes: true
    env:
      ID: "{{ node_index }}"
      CHAIN_ID: penumbra-testnet-deimos-8
      CMTHOME: /cometbft/testnet_data/node0/cometbft
      MONIKER: "{{ moniker }}"
      PROXY_APP: penumbra_container:26658
    volumes:
      - /testdata:/cometbft
    networks:
      - name: "{{ network_name }}"
    ports:
      - 0.0.0.0:26656:26656
      - 0.0.0.0:26657:26657
      - 0.0.0.0:26660:26660 #for metrics
