{
 "title": "DEX",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "DEX batch swaps duration",
   "type": "timeseries",
   "description": "Time spent executing all batch swaps",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(penumbra_dex_batch_duration_seconds_bucket[$__rate_interval])) by (le))\n",
     "legendFormat": "99th %ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(penumbra_dex_batch_duration_seconds_bucket[$__rate_interval])) by (le))\n",
     "legendFormat": "95th %ile"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(penumbra_dex_batch_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "75th %ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(penumbra_dex_batch_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "50th %ile"
    }
   ]
  },
  {
   "title": "DEX arbitrage duration",
   "type": "timeseries",
   "description": "Time spent performing arb at the end of the block",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(penumbra_dex_arb_duration_seconds_bucket[$__rate_interval])) by (le))\n",
     "legendFormat": "99th %ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(penumbra_dex_arb_duration_seconds_bucket[$__rate_interval])) by (le))\n",
     "legendFormat": "95th %ile"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(penumbra_dex_arb_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "75th %ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(penumbra_dex_arb_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "50th %ile"
    }
   ]
  },
  {
   "title": "DEX path search duration",
   "type": "timeseries",
   "description": "Time spent searching for paths while executing trades",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(penumbra_dex_path_search_duration_seconds_bucket[$__rate_interval])) by (le))\n",
     "legendFormat": "99th %ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(penumbra_dex_path_search_duration_seconds_bucket[$__rate_interval])) by (le))\n",
     "legendFormat": "95th %ile"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(penumbra_dex_path_search_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "75th %ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(penumbra_dex_path_search_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "50th %ile"
    }
   ]
  },
  {
   "title": "DEX fill_route duration",
   "type": "timeseries",
   "description": "Time spent filling routes while executing trades",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(penumbra_dex_route_fill_duration_seconds_bucket[$__rate_interval])) by (le))\n",
     "legendFormat": "99th %ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(penumbra_dex_route_fill_duration_seconds_bucket[$__rate_interval])) by (le))\n",
     "legendFormat": "95th %ile"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(penumbra_dex_route_fill_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "75th %ile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(penumbra_dex_route_fill_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "50th %ile"
    }
   ]
  }
 ]
}