---
- name: Ensure destination directory exists
  ansible.builtin.file:
    path: /pz
    state: directory
    mode: "0777"

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: /opt/cometbft
    state: directory
    mode: "0777"

- name: Copy Dockerfile template to target machine
  ansible.builtin.copy:
    src: ../files/Dockerfile
    dest: /pz

- name: Copy pd-init.sh script to target machine
  ansible.builtin.copy:
    src: ../files/pd-init.sh
    dest: /pz
    mode: "0755" # Ensure the script has executable permissions

- name: Copy init-volume.sh script to target machine
  ansible.builtin.copy:
    src: ../files/init-volume.sh
    dest: /pz
    mode: "0755" # Ensure the script has executable permissions

- name: Copy node.json to target machine
  ansible.builtin.copy:
    src: ../files/nodes.json
    dest: /pz
    mode: "0755" # Ensure the script has executable permissions

- name: Copy SQL file in target machine
  ansible.builtin.copy:
    src: ../files/cometbft-schema.sql
    dest: /opt/cometbft
