---
- name: Install required system packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - postgresql
      - libpq-dev
      - python3-psycopg2
    state: present
    update_cache: true

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Ensure Docker is installed
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Ensure Docker is started and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
- name: "Create docker network: {{ network_name }}"
  ansible.builtin.docker_network:
    name: "{{ network_name }}"
    driver: bridge
# - name: Create a Docker volume for Penumbra
#   community.docker.docker_volume:
#     name: penumbra_volume
#     driver_options:
#       type: tmpfs
#       device: /dev/sda1
#       o: "size={{data_volume_size}},rw"
#   register: docker_volume
