---
- name: Pull PostgreSQL image
  ansible.builtin.docker_image:
    name: ghcr.io/cloudnative-pg/postgresql
    tag: 13.15-1-bookworm
    source: pull

- name: Create data container
  community.general.docker_container:
    name: "{{ postgres_container_name }}-data"
    image: ghcr.io/cloudnative-pg/postgresql:13.15-1-bookworm
    state: present

- name: Run PostgreSQL container
  community.general.docker_container:
    name: "{{ postgres_container_name }}"
    image: ghcr.io/cloudnative-pg/postgresql:13.15-1-bookworm
    restart_policy: always
    state: started
    memory: "{{ postgres_memory_limit | default(omit) }}"
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_USER: "{{ postgres_user }}"
    volumes_from:
      - "{{ postgres_container_name }}-data"
    published_ports:
      - "{{ postgres_port }}:{{ postgres_port }}"
    networks:
      - name: "{{ network_name }}"
  register: postgres_container

- name: Wait for postgresSql starts up
  ansible.builtin.wait_for:
    port: "{{ postgres_port }}"
    delay: 5
  when: postgres_container.changed

- name: Run queries from SQL script
  community.postgresql.postgresql_script:
    host: localhost
    port: "{{ postgres_port }}"
    login_user: "{{ postgres_user }}"
    login_password: "{{ postgres_password }}"
    db: "{{ postgres_database }}"
    path: /opt/cometbft/cometbft-schema.sql
